import StarIcon from "@mui/icons-material/Star";
export const cardsItem = [
    {
      img: "./images/image 24.png",
      title: "Va di Funes",
      rating: "4.7",
      star: <StarIcon />,
      day: "3Days 4Nights",
      text1: "Tour combo with return airport transter",
      text2: "City Tour",
      text3: "Curios Center",
      type1: "₹88,952",
      type2: "₹88,952",
      type3: "Per person",
      iconname: "2 Flights",
      iconURL: "/images/icon1.png",
      iconnametwo: "1 Hotel",
      icontwoURL: "/images/icon2.png",
      iconnamethree: "2 Transfers",
      iconthreeURL: "/images/icon3.png",
      iconnamefour: "4 Activities",
      icontourURL: "/images/icon4.png",
    },
    {
      img: "./images/image 25.png",
      title: "Ushuila",
      rating: "4.7",
      star: <StarIcon />,
      day: "3Days 4Nights",
      text1: "Tour combo with return airport transter",
      text2: "City Tour",
      text3: "Curios Center",
      type1: "₹88,952",
      type2: "₹88,952",
      type3: "Per person",
      iconname: "2 Flights",
      iconURL: "/images/icon1.png",
      iconnametwo: "1 Hotel",
      icontwoURL: "/images/icon2.png",
      iconnamethree: "2 Transfers",
      iconthreeURL: "/images/icon3.png",
      iconnamefour: "4 Activities",
      icontourURL: "/images/icon4.png",
    },
    {
      img: "./images/image 31.png",
      title: "Berchtesgaden",
      rating: "4.7",
      star: <StarIcon />,
      day: "3Days 4Nights",
      text1: "Tour combo with return airport transter",
      text2: "City Tour",
      text3: "Curios Center",
      type1: "₹88,952",
      type2: "₹88,952",
      type3: "Per person",
      iconname: "2 Flights",
      iconURL: "/images/icon1.png",
      iconnametwo: "1 Hotel",
      icontwoURL: "/images/icon2.png",
      iconnamethree: "2 Transfers",
      iconthreeURL: "/images/icon3.png",
      iconnamefour: "4 Activities",
      icontourURL: "/images/icon4.png",
    },
    {
      img: "./images/image 32.png",
      title: "Fussen",
      rating: "4.7",
      star: <StarIcon />,
      day: "3Days 4Nights",
      text1: "Tour combo with return airport transter",
      text2: "City Tour",
      text3: "Curios Center",
      type1: "₹88,952",
      type2: "₹88,952",
      type3: "Per person",
      iconname: "2 Flights",
      iconURL: "/images/icon1.png",
      iconnametwo: "1 Hotel",
      icontwoURL: "/images/icon2.png",
      iconnamethree: "2 Transfers",
      iconthreeURL: "/images/icon3.png",
      iconnamefour: "4 Activities",
      icontourURL: "/images/icon4.png",
    },
  ];